#
# This compose file spins up a redis + postgres container for development
#

services:
  content-repo:
    image: containers.r0b.io/repo-api-service:0.3.6
    platform: linux/amd64
    volumes:
      - ./content:/app/repo/content
    ports:
      - '127.0.0.1:9000:8000'
