name: Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - config/base/**
      - config/overlays/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo -n "$KUBE_CONFIG" > $HOME/.kube/config

      # - name: deploy
      #   run: |
      #     kubectl apply -k config/overlays/production
