#
# Builds a server + client container tagged under a commit's hash when a PR is updated
#
# refs:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images
# - https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
#

name: Build PR Containers

on:
  pull_request:
    branches: [main]

env:
  CLIENT_REGISTRY: ghcr.io/digitalinteraction/mozfest-client
  SERVER_REGISTRY: ghcr.io/digitalinteraction/mozfest-server

jobs:
  build_containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate client metadata
        id: client_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.CLIENT_REGISTRY }}
          tags: |
            type=sha

      - name: Generate server metadata
        id: server_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.SERVER_REGISTRY }}
          tags: |
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push / client
        uses: docker/build-push-action@v3
        with:
          context: client
          push: true
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}

      - name: Build and push / server
        uses: docker/build-push-action@v3
        with:
          context: server
          push: true
          tags: ${{ steps.server_meta.outputs.tags }}
          labels: ${{ steps.server_meta.outputs.labels }}
